name: AndroidBuild


on:
  pull_request:
    braches: [ main ]
  push:
    branches: [ main ]

jobs:
  build:
    run-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/chekout@4.1.0

      - name: setup Java JDK
        uses: actions/setup-java@3.13.0
        with:
          java-version : '1.8'
          distirbution : 'adopt'

      - name: Build with gradle
        run: ./gradlew build

      - name: Upload a build artifact
        uses: actions/upload-artifact@3.1.3
        with:
          name: AnrdoidCICD.apk
          path: app/build/outputs/apk/debug/app-debug.apk
